export const Questions
[
    {   "testkey" : "12345",
        "teacher_username" : "admin",
        "semester": "1",
        "question": "Question for SEM 1",
        "optionA": "SEM1",
        "optionB": "SEM3",
        "optionC": "SEM8",
        "optionD": "SEM9",
        "answer": "A",
        "quizname": "admin_test"
    },
    {   "testkey" : "12345",
        "teacher_username" : "admin",
        "semester": "1",
        "question": "RQP, ONM, _, IHG, FED, find the missing letters.",
        "optionA": "CDE",
        "optionB": "LKI",
        "optionC": "LKJ",
        "optionD": "BAC",
        "answer": "C",
        "quizname": "admin_test"
    },
    {   "testkey" : "12345",
        "teacher_username" : "admin",
        "semester": "1",
        "question": " PETAL: FLOWER",
        "optionA": "Pen: Paper",
        "optionB": "Engine: Car",
        "optionC": "Cat: Dog",
        "optionD": "Ball: Game",
        "answer": "B",
        "quizname": "admin_test"
    },
    {   "testkey" : "12345",
        "teacher_username" : "admin",
        "semester": "1",
        "question": "Arrange the following words in a meaningful sequence.1. Cow 2. Grass 3. Milk 4. Curd 5. Butter",
        "optionA": "1, 3, 2, 4, 5",
        "optionB": "4, 3, 5, 1, 2",
        "optionC": "3, 4, 5, 1, 2",
        "optionD": "1, 2, 3, 4, 5",
        "answer": "D",
        "quizname": "admin_test"
    },
    {   "testkey" : "12345",
        "teacher_username" : "admin",
        "semester": "1",
        "question": " Pointing to a photograph, a man said, 'I have no brother, and that man's father is my father's son.' Whose photograph was it?",
        "optionA": "His son",
        "optionB": "His own",
        "optionC": "His father",
        "optionD": "His nephew",
        "answer": "A",
        "quizname": "admin_test"
    },
    {   "testkey" : "12345",
        "teacher_username" : "admin",
        "semester": "1",
        "question": "Peter is in the East of Tom and Tom is in the North of John. Mike is in the South of John then in which direction of Peter is Mike?",
        "optionA": "South-East",
        "optionB": "South-West",
        "optionC": "South",
        "optionD": "North-East",
        "answer": "B",
        "quizname": "admin_test"
    },

    {   "testkey" : "12345",
        "teacher_username" : "admin",
        "semester": "1",
        "question": " An animal always has",
        "optionA": "Skin",
        "optionB": "Heart",
        "optionC": "Lungs",
        "optionD": "life",
        "answer": "D",
        "quizname": "admin_test"
    },
    
    {   "testkey" : "12345",
        "teacher_username" : "admin",
        "semester": "1",
        "question": "Which word does not belong to others?",
        "optionA": "Violin",
        "optionB": "Guitar",
        "optionC": "Flute",
        "optionD": "Mandolin",
        "answer": "C",
        "quizname": "admin_test"
    },
    {   "testkey" : "12345",
        "teacher_username" : "admin",
        "semester": "1",
        "question": "What are the missing numbers in this series, 15, 20, 24, 15, 28, 32 15, _, _, 15?",
        "optionA": "37, 41",
        "optionB": "36, 40",
        "optionC": "38, 42",
        "optionD": "40, 44",
        "answer": "B",
        "quizname": "admin_test"
    },
    {   "testkey" : "12345",
        "teacher_username" : "admin",
        "semester": "1",
        "question": "If HOT is coded as GNS, How is COLD coded?",
        "optionA": "BNKC",
        "optionB": "DPME",
        "optionC": "EQNF",
        "optionD": "FROG",
        "answer": "A",
        "quizname": "admin_test"
    },
    
   //sem2 
    {   "testkey" : "223",
        "teacher_username" : "admin",
        "semester": "2",
        "question": "Question for SEM 2",
        "optionA": "SEM1",
        "optionB": "SEM3",
        "optionC": "SEM2",
        "optionD": "SEM9",
        "answer": "C",
        "quizname": "admin_test"
    },
    {   "testkey" : "223",
        "teacher_username" : "admin",
        "semester": "2",
        "question": "RQP, ONM, _, IHG, FED, find the missing letters.",
        "optionA": "CDE",
        "optionB": "LKI",
        "optionC": "LKJ",
        "optionD": "BAC",
        "answer": "C",
        "quizname": "admin_test"
    },
    {   "testkey" : "223",
        "teacher_username" : "admin",
        "semester": "2",
        "question": " PETAL: FLOWER",
        "optionA": "Pen: Paper",
        "optionB": "Engine: Car",
        "optionC": "Cat: Dog",
        "optionD": "Ball: Game",
        "answer": "B",
         "quizname": "admin_test"
    },
    {   "testkey" : "223",
        "teacher_username" : "admin",
        "semester": "2",
        "question": "Arrange the following words in a meaningful sequence.1. Cow 2. Grass 3. Milk 4. Curd 5. Butter",
        "optionA": "1, 3, 2, 4, 5",
        "optionB": "4, 3, 5, 1, 2",
        "optionC": "3, 4, 5, 1, 2",
        "optionD": "1, 2, 3, 4, 5",
        "answer": "D",
         "quizname": "admin_test"
    },
    {   "testkey" : "223",
        "teacher_username" : "admin",
        "semester": "2",
        "question": " Pointing to a photograph, a man said, 'I have no brother, and that man's father is my father's son.' Whose photograph was it?",
        "optionA": "His son",
        "optionB": "His own",
        "optionC": "His father",
        "optionD": "His nephew",
        "answer": "A",
         "quizname": "admin_test"
    },
    {   "testkey" : "223",
        "teacher_username" : "admin",
        "semester": "2",
        "question": "Peter is in the East of Tom and Tom is in the North of John. Mike is in the South of John then in which direction of Peter is Mike?",
        "optionA": "South-East",
        "optionB": "South-West",
        "optionC": "South",
        "optionD": "North-East",
        "answer": "B",
         "quizname": "admin_test"
    },

    {   "testkey" : "223",
        "teacher_username" : "admin",
        "semester": "2",
        "question": " An animal always has",
        "optionA": "Skin",
        "optionB": "Heart",
        "optionC": "Lungs",
        "optionD": "life",
        "answer": "D",
         "quizname": "admin_test"
    },
    
    {   "testkey" : "223",
        "teacher_username" : "admin",
        "semester": "2",
        "question": "Which word does not belong to others?",
        "optionA": "Violin",
        "optionB": "Guitar",
        "optionC": "Flute",
        "optionD": "Mandolin",
        "answer": "C",
         "quizname": "admin_test"
    },
    {   "testkey" : "223",
        "teacher_username" : "admin",
        "semester": "2",
        "question": "What are the missing numbers in this series, 15, 20, 24, 15, 28, 32 15, _, _, 15?",
        "optionA": "37, 41",
        "optionB": "36, 40",
        "optionC": "38, 42",
        "optionD": "40, 44",
        "answer": "B", 
        "quizname": "admin_test"
    },
    {   "testkey" : "223",
        "teacher_username" : "admin",
        "semester": "2",
        "question": "If HOT is coded as GNS, How is COLD coded?",
        "optionA": "BNKC",
        "optionB": "DPME",
        "optionC": "EQNF",
        "optionD": "FROG",
        "answer": "A",
        "quizname": "admin_test"
    },

    //sem3
    {   "testkey" : "323",
        "teacher_username" : "admin",
        "semester": "3",
        "question": "Question for SEM 3",
        "optionA": "SEM1",
        "optionB": "SEM3",
        "optionC": "SEM2",
        "optionD": "SEM9",
        "answer": "B",
        "quizname": "admin_test"
    },
    {   "testkey" : "323",
        "teacher_username" : "admin",
        "semester": "3",
        "question": "RQP, ONM, _, IHG, FED, find the missing letters.",
        "optionA": "CDE",
        "optionB": "LKI",
        "optionC": "LKJ",
        "optionD": "BAC",
        "answer": "C",
        "quizname": "admin_test"
    },
    {   "testkey" : "323",
        "teacher_username" : "admin",
        "semester": "3",
        "question": " PETAL: FLOWER",
        "optionA": "Pen: Paper",
        "optionB": "Engine: Car",
        "optionC": "Cat: Dog",
        "optionD": "Ball: Game",
        "answer": "B",
        "quizname": "admin_test"
    },
    {   "testkey" : "323",
        "teacher_username" : "admin",
        "semester": "3",
        "question": "Arrange the following words in a meaningful sequence.1. Cow 2. Grass 3. Milk 4. Curd 5. Butter",
        "optionA": "1, 3, 2, 4, 5",
        "optionB": "4, 3, 5, 1, 2",
        "optionC": "3, 4, 5, 1, 2",
        "optionD": "1, 2, 3, 4, 5",
        "answer": "D",
        "quizname": "admin_test"
    },
    {   "testkey" : "323",
        "teacher_username" : "admin",
        "semester": "3",
        "question": " Pointing to a photograph, a man said, 'I have no brother, and that man's father is my father's son.' Whose photograph was it?",
        "optionA": "His son",
        "optionB": "His own",
        "optionC": "His father",
        "optionD": "His nephew",
        "answer": "A",
        "quizname": "admin_test"
    },
    {   "testkey" : "323",
        "teacher_username" : "admin",
        "semester": "3",
        "question": "Peter is in the East of Tom and Tom is in the North of John. Mike is in the South of John then in which direction of Peter is Mike?",
        "optionA": "South-East",
        "optionB": "South-West",
        "optionC": "South",
        "optionD": "North-East",
        "answer": "B",
        "quizname": "admin_test"
    },

    {   "testkey" : "323",
        "teacher_username" : "admin",
        "semester": "3",
        "question": " An animal always has",
        "optionA": "Skin",
        "optionB": "Heart",
        "optionC": "Lungs",
        "optionD": "life",
        "answer": "D",
        "quizname": "admin_test"
    },
    
    {   "testkey" : "323",
        "teacher_username" : "admin",
        "semester": "3",
        "question": "Which word does not belong to others?",
        "optionA": "Violin",
        "optionB": "Guitar",
        "optionC": "Flute",
        "optionD": "Mandolin",
        "answer": "C",
        "quizname": "admin_test"
    },
    {   "testkey" : "323",
        "teacher_username" : "admin",
        "semester": "3",
        "question": "What are the missing numbers in this series, 15, 20, 24, 15, 28, 32 15, _, _, 15?",
        "optionA": "37, 41",
        "optionB": "36, 40",
        "optionC": "38, 42",
        "optionD": "40, 44",
        "answer": "B",
        "quizname": "admin_test"
    },
    {   "testkey" : "323",
        "teacher_username" : "admin",
        "semester": "3",
        "question": "If HOT is coded as GNS, How is COLD coded?",
        "optionA": "BNKC",
        "optionB": "DPME",
        "optionC": "EQNF",
        "optionD": "FROG",
        "answer": "A",
        "quizname": "admin_test"
    },
    
 
   //sem 4
   {   
    "testkey" : "423",
   "teacher_username" : "admin",
   "semester": "4",
   "question": "Question for SEM 4",
   "optionA": "SEM1",
   "optionB": "SEM3",
   "optionC": "SEM4",
   "optionD": "SEM9",
   "answer": "C",
   "quizname": "admin_test"
},
{   "testkey" : "423",
   "teacher_username" : "admin",
   "semester": "4",
   "question": "RQP, ONM, _, IHG, FED, find the missing letters.",
   "optionA": "CDE",
   "optionB": "LKI",
   "optionC": "LKJ",
   "optionD": "BAC",
   "answer": "C",
   "quizname": "admin_test"
},
{   "testkey" : "423",
   "teacher_username" : "admin",
   "semester": "4",
   "question": " PETAL: FLOWER",
   "optionA": "Pen: Paper",
   "optionB": "Engine: Car",
   "optionC": "Cat: Dog",
   "optionD": "Ball: Game",
   "answer": "B",
   "quizname": "admin_test"
},
{   "testkey" : "423",
   "teacher_username" : "admin",
   "semester": "4",
   "question": "Arrange the following words in a meaningful sequence.1. Cow 2. Grass 3. Milk 4. Curd 5. Butter",
   "optionA": "1, 3, 2, 4, 5",
   "optionB": "4, 3, 5, 1, 2",
   "optionC": "3, 4, 5, 1, 2",
   "optionD": "1, 2, 3, 4, 5",
   "answer": "D",
   "quizname": "admin_test"
},
{   "testkey" : "423",
   "teacher_username" : "admin",
   "semester": "4",
   "question": " Pointing to a photograph, a man said, 'I have no brother, and that man's father is my father's son.' Whose photograph was it?",
   "optionA": "His son",
   "optionB": "His own",
   "optionC": "His father",
   "optionD": "His nephew",
   "answer": "A",
   "quizname": "admin_test"
},
{   "testkey" : "423",
   "teacher_username" : "admin",
   "semester": "4",
   "question": "Peter is in the East of Tom and Tom is in the North of John. Mike is in the South of John then in which direction of Peter is Mike?",
   "optionA": "South-East",
   "optionB": "South-West",
   "optionC": "South",
   "optionD": "North-East",
   "answer": "B",
   "quizname": "admin_test"
},

{   "testkey" : "423",
   "teacher_username" : "admin",
   "semester": "4",
   "question": " An animal always has",
   "optionA": "Skin",
   "optionB": "Heart",
   "optionC": "Lungs",
   "optionD": "life",
   "answer": "D",
   "quizname": "admin_test"
},

{   "testkey" : "423",
   "teacher_username" : "admin",
   "semester": "4",
   "question": "Which word does not belong to others?",
   "optionA": "Violin",
   "optionB": "Guitar",
   "optionC": "Flute",
   "optionD": "Mandolin",
   "answer": "C",
   "quizname": "admin_test"
},
{   "testkey" : "423",
   "teacher_username" : "admin",
   "semester": "4",
   "question": "What are the missing numbers in this series, 15, 20, 24, 15, 28, 32 15, _, _, 15?",
   "optionA": "37, 41",
   "optionB": "36, 40",
   "optionC": "38, 42",
   "optionD": "40, 44",
   "answer": "B",
   "quizname": "admin_test"
},
{   "testkey" : "423",
   "teacher_username" : "admin",
   "semester": "4",
   "question": "If HOT is coded as GNS, How is COLD coded?",
   "optionA": "BNKC",
   "optionB": "DPME",
   "optionC": "EQNF",
   "optionD": "FROG",
   "answer": "A",
   "quizname": "admin_test"
},

   //sem 5
   {   
    "testkey" : "523",
   "teacher_username" : "admin",
   "semester": "5",
   "question": "Question for SEM 5",
   "optionA": "SEM1",
   "optionB": "SEM3",
   "optionC": "SEM5",
   "optionD": "SEM9",
   "answer": "C",
   "quizname": "admin_test"
},
{   "testkey" : "523",
   "teacher_username" : "admin",
   "semester": "5",
   "question": "RQP, ONM, _, IHG, FED, find the missing letters.",
   "optionA": "CDE",
   "optionB": "LKI",
   "optionC": "LKJ",
   "optionD": "BAC",
   "answer": "C",
   "quizname": "admin_test"
},
{   "testkey" : "523",
   "teacher_username" : "admin",
   "semester": "5",
   "question": " PETAL: FLOWER",
   "optionA": "Pen: Paper",
   "optionB": "Engine: Car",
   "optionC": "Cat: Dog",
   "optionD": "Ball: Game",
   "answer": "B",
   "quizname": "admin_test"
},
{   "testkey" : "523",
   "teacher_username" : "admin",
   "semester": "5",
   "question": "Arrange the following words in a meaningful sequence.1. Cow 2. Grass 3. Milk 4. Curd 5. Butter",
   "optionA": "1, 3, 2, 4, 5",
   "optionB": "4, 3, 5, 1, 2",
   "optionC": "3, 4, 5, 1, 2",
   "optionD": "1, 2, 3, 4, 5",
   "answer": "D",
   "quizname": "admin_test"
},
{   "testkey" : "523",
   "teacher_username" : "admin",
   "semester": "5",
   "question": " Pointing to a photograph, a man said, 'I have no brother, and that man's father is my father's son.' Whose photograph was it?",
   "optionA": "His son",
   "optionB": "His own",
   "optionC": "His father",
   "optionD": "His nephew",
   "answer": "A",
   "quizname": "admin_test"
},
{   "testkey" : "523",
   "teacher_username" : "admin",
   "semester": "5",
   "question": "Peter is in the East of Tom and Tom is in the North of John. Mike is in the South of John then in which direction of Peter is Mike?",
   "optionA": "South-East",
   "optionB": "South-West",
   "optionC": "South",
   "optionD": "North-East",
   "answer": "B",
   "quizname": "admin_test"
},

{   "testkey" : "523",
   "teacher_username" : "admin",
   "semester": "5",
   "question": " An animal always has",
   "optionA": "Skin",
   "optionB": "Heart",
   "optionC": "Lungs",
   "optionD": "life",
   "answer": "D",
   "quizname": "admin_test"
},

{   "testkey" : "523",
   "teacher_username" : "admin",
   "semester": "5",
   "question": "Which word does not belong to others?",
   "optionA": "Violin",
   "optionB": "Guitar",
   "optionC": "Flute",
   "optionD": "Mandolin",
   "answer": "C",
   "quizname": "admin_test"
},
{   "testkey" : "523",
   "teacher_username" : "admin",
   "semester": "5",
   "question": "What are the missing numbers in this series, 15, 20, 24, 15, 28, 32 15, _, _, 15?",
   "optionA": "37, 41",
   "optionB": "36, 40",
   "optionC": "38, 42",
   "optionD": "40, 44",
   "answer": "B",
   "quizname": "admin_test"
},
{   "testkey" : "523",
   "teacher_username" : "admin",
   "semester": "5",
   "question": "If HOT is coded as GNS, How is COLD coded?",
   "optionA": "BNKC",
   "optionB": "DPME",
   "optionC": "EQNF",
   "optionD": "FROG",
   "answer": "A",
   "quizname": "admin_test"
},

   //sem 6
   {   
    "testkey" : "623",
   "teacher_username" : "admin",
   "semester": "6",
   "question": "Question for SEM 6",
   "optionA": "SEM1",
   "optionB": "SEM3",
   "optionC": "SEM6",
   "optionD": "SEM9",
   "answer": "C",
   "quizname": "admin_test"
},
{   "testkey" : "623",
   "teacher_username" : "admin",
   "semester": "6",
   "question": "RQP, ONM, _, IHG, FED, find the missing letters.",
   "optionA": "CDE",
   "optionB": "LKI",
   "optionC": "LKJ",
   "optionD": "BAC",
   "answer": "C",
   "quizname": "admin_test"
},
{   "testkey" : "623",
   "teacher_username" : "admin",
   "semester": "6",
   "question": " PETAL: FLOWER",
   "optionA": "Pen: Paper",
   "optionB": "Engine: Car",
   "optionC": "Cat: Dog",
   "optionD": "Ball: Game",
   "answer": "B",
   "quizname": "admin_test"
},
{   "testkey" : "623",
   "teacher_username" : "admin",
   "semester": "6",
   "question": "Arrange the following words in a meaningful sequence.1. Cow 2. Grass 3. Milk 4. Curd 5. Butter",
   "optionA": "1, 3, 2, 4, 5",
   "optionB": "4, 3, 5, 1, 2",
   "optionC": "3, 4, 5, 1, 2",
   "optionD": "1, 2, 3, 4, 5",
   "answer": "D",
   "quizname": "admin_test"
},
{   "testkey" : "623",
   "teacher_username" : "admin",
   "semester": "6",
   "question": " Pointing to a photograph, a man said, 'I have no brother, and that man's father is my father's son.' Whose photograph was it?",
   "optionA": "His son",
   "optionB": "His own",
   "optionC": "His father",
   "optionD": "His nephew",
   "answer": "A",
   "quizname": "admin_test"
},
{   "testkey" : "623",
   "teacher_username" : "admin",
   "semester": "6",
   "question": "Peter is in the East of Tom and Tom is in the North of John. Mike is in the South of John then in which direction of Peter is Mike?",
   "optionA": "South-East",
   "optionB": "South-West",
   "optionC": "South",
   "optionD": "North-East",
   "answer": "B",
   "quizname": "admin_test"
},

{   "testkey" : "623",
   "teacher_username" : "admin",
   "semester": "6",
   "question": " An animal always has",
   "optionA": "Skin",
   "optionB": "Heart",
   "optionC": "Lungs",
   "optionD": "life",
   "answer": "D",
   "quizname": "admin_test"
},

{   "testkey" : "623",
   "teacher_username" : "admin",
   "semester": "6",
   "question": "Which word does not belong to others?",
   "optionA": "Violin",
   "optionB": "Guitar",
   "optionC": "Flute",
   "optionD": "Mandolin",
   "answer": "C",
   "quizname": "admin_test"
},
{   "testkey" : "623",
   "teacher_username" : "admin",
   "semester": "6",
   "question": "What are the missing numbers in this series, 15, 20, 24, 15, 28, 32 15, _, _, 15?",
   "optionA": "37, 41",
   "optionB": "36, 40",
   "optionC": "38, 42",
   "optionD": "40, 44",
   "answer": "B",
   "quizname": "admin_test"
},
{   "testkey" : "623",
   "teacher_username" : "admin",
   "semester": "6",
   "question": "If HOT is coded as GNS, How is COLD coded?",
   "optionA": "BNKC",
   "optionB": "DPME",
   "optionC": "EQNF",
   "optionD": "FROG",
   "answer": "A",
   "quizname": "admin_test"
},

//sem 7
{   
    "testkey" : "723",
   "teacher_username" : "admin",
   "semester": "7",
   "question": "Question for SEM 7",
   "optionA": "SEM1",
   "optionB": "SEM3",
   "optionC": "SEM7",
   "optionD": "SEM9",
   "answer": "C",
   "quizname": "admin_test"
},
{   "testkey" : "723",
   "teacher_username" : "admin",
   "semester": "7",
   "question": "RQP, ONM, _, IHG, FED, find the missing letters.",
   "optionA": "CDE",
   "optionB": "LKI",
   "optionC": "LKJ",
   "optionD": "BAC",
   "answer": "C",
   "quizname": "admin_test"
},
{   "testkey" : "723",
   "teacher_username" : "admin",
   "semester": "7",
   "question": " PETAL: FLOWER",
   "optionA": "Pen: Paper",
   "optionB": "Engine: Car",
   "optionC": "Cat: Dog",
   "optionD": "Ball: Game",
   "answer": "B",
   "quizname": "admin_test"
},
{   "testkey" : "723",
   "teacher_username" : "admin",
   "semester": "7",
   "question": "Arrange the following words in a meaningful sequence.1. Cow 2. Grass 3. Milk 4. Curd 5. Butter",
   "optionA": "1, 3, 2, 4, 5",
   "optionB": "4, 3, 5, 1, 2",
   "optionC": "3, 4, 5, 1, 2",
   "optionD": "1, 2, 3, 4, 5",
   "answer": "D",
   "quizname": "admin_test"
},
{   "testkey" : "723",
   "teacher_username" : "admin",
   "semester": "7",
   "question": " Pointing to a photograph, a man said, 'I have no brother, and that man's father is my father's son.' Whose photograph was it?",
   "optionA": "His son",
   "optionB": "His own",
   "optionC": "His father",
   "optionD": "His nephew",
   "answer": "A",
   "quizname": "admin_test"
},
{   "testkey" : "723",
   "teacher_username" : "admin",
   "semester": "7",
   "question": "Peter is in the East of Tom and Tom is in the North of John. Mike is in the South of John then in which direction of Peter is Mike?",
   "optionA": "South-East",
   "optionB": "South-West",
   "optionC": "South",
   "optionD": "North-East",
   "answer": "B",
   "quizname": "admin_test"
},

{   "testkey" : "723",
   "teacher_username" : "admin",
   "semester": "7",
   "question": " An animal always has",
   "optionA": "Skin",
   "optionB": "Heart",
   "optionC": "Lungs",
   "optionD": "life",
   "answer": "D",
   "quizname": "admin_test"
},

{   "testkey" : "723",
   "teacher_username" : "admin",
   "semester": "7",
   "question": "Which word does not belong to others?",
   "optionA": "Violin",
   "optionB": "Guitar",
   "optionC": "Flute",
   "optionD": "Mandolin",
   "answer": "C",
   "quizname": "admin_test"
},
{   "testkey" : "723",
   "teacher_username" : "admin",
   "semester": "7",
   "question": "What are the missing numbers in this series, 15, 20, 24, 15, 28, 32 15, _, _, 15?",
   "optionA": "37, 41",
   "optionB": "36, 40",
   "optionC": "38, 42",
   "optionD": "40, 44",
   "answer": "B",
   "quizname": "admin_test"
},
{   "testkey" : "723",
   "teacher_username" : "admin",
   "semester": "7",
   "question": "If HOT is coded as GNS, How is COLD coded?",
   "optionA": "BNKC",
   "optionB": "DPME",
   "optionC": "EQNF",
   "optionD": "FROG",
   "answer": "A",
   "quizname": "admin_test"
},

//sem 8
{   
    "testkey" : "823",
   "teacher_username" : "admin",
   "semester": "8",
   "question": "Question for SEM 8",
   "optionA": "SEM1",
   "optionB": "SEM3",
   "optionC": "SEM8",
   "optionD": "SEM9",
   "answer": "C",
   "quizname": "admin_test"
},
{   "testkey" : "823",
   "teacher_username" : "admin",
   "semester": "8",
   "question": "RQP, ONM, _, IHG, FED, find the missing letters.",
   "optionA": "CDE",
   "optionB": "LKI",
   "optionC": "LKJ",
   "optionD": "BAC",
   "answer": "C",
   "quizname": "admin_test"
},
{   "testkey" : "823",
   "teacher_username" : "admin",
   "semester": "8",
   "question": " PETAL: FLOWER",
   "optionA": "Pen: Paper",
   "optionB": "Engine: Car",
   "optionC": "Cat: Dog",
   "optionD": "Ball: Game",
   "answer": "B",
   "quizname": "admin_test"
},
{   "testkey" : "823",
   "teacher_username" : "admin",
   "semester": "8",
   "question": "Arrange the following words in a meaningful sequence.1. Cow 2. Grass 3. Milk 4. Curd 5. Butter",
   "optionA": "1, 3, 2, 4, 5",
   "optionB": "4, 3, 5, 1, 2",
   "optionC": "3, 4, 5, 1, 2",
   "optionD": "1, 2, 3, 4, 5",
   "answer": "D",
   "quizname": "admin_test"
},
{   "testkey" : "823",
   "teacher_username" : "admin",
   "semester": "8",
   "question": " Pointing to a photograph, a man said, 'I have no brother, and that man's father is my father's son.' Whose photograph was it?",
   "optionA": "His son",
   "optionB": "His own",
   "optionC": "His father",
   "optionD": "His nephew",
   "answer": "A",
   "quizname": "admin_test"
},
{   "testkey" : "823",
   "teacher_username" : "admin",
   "semester": "8",
   "question": "Peter is in the East of Tom and Tom is in the North of John. Mike is in the South of John then in which direction of Peter is Mike?",
   "optionA": "South-East",
   "optionB": "South-West",
   "optionC": "South",
   "optionD": "North-East",
   "answer": "B",
   "quizname": "admin_test"
},

{   "testkey" : "823",
   "teacher_username" : "admin",
   "semester": "8",
   "question": " An animal always has",
   "optionA": "Skin",
   "optionB": "Heart",
   "optionC": "Lungs",
   "optionD": "life",
   "answer": "D",
   "quizname": "admin_test"
},

{   "testkey" : "823",
   "teacher_username" : "admin",
   "semester": "8",
   "question": "Which word does not belong to others?",
   "optionA": "Violin",
   "optionB": "Guitar",
   "optionC": "Flute",
   "optionD": "Mandolin",
   "answer": "C",
   "quizname": "admin_test"
},
{   "testkey" : "823",
   "teacher_username" : "admin",
   "semester": "8",
   "question": "What are the missing numbers in this series, 15, 20, 24, 15, 28, 32 15, _, _, 15?",
   "optionA": "37, 41",
   "optionB": "36, 40",
   "optionC": "38, 42",
   "optionD": "40, 44",
   "answer": "B",
   "quizname": "admin_test"
},
{   "testkey" : "823",
   "teacher_username" : "admin",
   "semester": "8",
   "question": "If HOT is coded as GNS, How is COLD coded?",
   "optionA": "BNKC",
   "optionB": "DPME",
   "optionC": "EQNF",
   "optionD": "FROG",
   "answer": "A",
   "quizname": "admin_test"
}


]