# Generated by Django 3.0.5 on 2022-03-18 15:09

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('username', models.CharField(default='', max_length=20)),
                ('suggestions', models.TextField()),
                ('avgtotal', models.IntegerField()),
                ('endorsement', models.CharField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.IntegerField()),
                ('Student_username', models.CharField(default='', max_length=200)),
                ('college_name', models.CharField(default='', max_length=200)),
                ('student_name', models.CharField(default='', max_length=200)),
                ('branch', models.CharField(default='', max_length=200)),
                ('semester', models.CharField(default='', max_length=200)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_mobile', models.CharField(default='', max_length=200)),
                ('ssc_mks', models.CharField(default='', max_length=200)),
                ('hsc_mks', models.CharField(default='', max_length=200)),
                ('technical_skills', models.TextField()),
                ('cgpa', models.CharField(default='', max_length=200)),
                ('alternative_email', models.CharField(default='', max_length=200)),
                ('alternative_mobile', models.CharField(default='', max_length=200)),
                ('yop', models.CharField(default='', max_length=200)),
                ('linkedin', models.URLField()),
                ('resume', models.FileField(default='settings.MEDIA_ROOT/resumes/Resume.pdf', upload_to='JobResumes/')),
            ],
        ),
        migrations.CreateModel(
            name='Newproj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=100)),
                ('Semester', models.CharField(max_length=100)),
                ('Roll_no', models.IntegerField()),
                ('Div', models.CharField(max_length=5)),
                ('Project_name', models.CharField(max_length=100)),
                ('Subject', models.CharField(max_length=100)),
                ('Teacher_username', models.CharField(max_length=100)),
                ('Project_description', models.TextField()),
                ('Git_link', models.URLField()),
                ('Project_members', models.CharField(max_length=200)),
                ('Output_File', models.FileField(default='settings.MEDIA_ROOT/projectfiles/sample.docx', upload_to='projectfiles/')),
            ],
        ),
        migrations.CreateModel(
            name='nproj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('sem', models.CharField(max_length=100)),
                ('rno', models.IntegerField()),
                ('div', models.CharField(max_length=5)),
                ('pname', models.CharField(max_length=100)),
                ('subj', models.CharField(max_length=100)),
                ('tuser', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('git', models.URLField()),
                ('pmem', models.CharField(max_length=200)),
                ('file', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('gender', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='Maharashtra', max_length=100)),
                ('city', models.CharField(default='Mumbai', max_length=100)),
                ('specialization', models.CharField(default='', max_length=200)),
                ('organization', models.CharField(default='', max_length=200)),
                ('yos', models.CharField(default='', max_length=100)),
                ('course', models.CharField(default='', max_length=100)),
                ('dob', models.DateField(default='2000-07-12')),
                ('yop', models.CharField(default='', max_length=20)),
                ('mbno', models.CharField(default='', max_length=10)),
                ('linkedin', models.URLField()),
                ('github', models.URLField()),
                ('description', models.TextField(default='')),
                ('profile_image', models.ImageField(default='settings.MEDIA_ROOT/profile_img/s.png', upload_to='profile_img/')),
                ('sem_average_marks', models.FloatField(default=0)),
                ('language', models.CharField(default='', max_length=100)),
                ('current_sem', models.CharField(default='', max_length=30)),
                ('resume', models.FileField(default='settings.MEDIA_ROOT/resumes/Resume.pdf', upload_to='resumes/')),
                ('eq', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Questionbank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=5000)),
                ('optionA', models.CharField(max_length=500)),
                ('optionB', models.CharField(max_length=500)),
                ('optionC', models.CharField(max_length=500)),
                ('optionD', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
                ('testkey', models.CharField(max_length=10)),
                ('teacher_username', models.CharField(max_length=50)),
                ('quizname', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDashboard',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=(django.views.generic.base.TemplateView, 'auth.user'),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentsProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.FloatField()),
                ('student_username', models.CharField(max_length=50)),
                ('project_score', models.IntegerField()),
                ('sem_average_marks', models.IntegerField()),
                ('language', models.CharField(max_length=100)),
                ('current_sem', models.CharField(max_length=30)),
                ('resume', models.FileField(upload_to='resumes/')),
            ],
        ),
        migrations.CreateModel(
            name='Testscore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('testkey', models.CharField(max_length=10)),
                ('teacher_username', models.CharField(default='admin', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TestSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_username', models.CharField(max_length=50)),
                ('gaming_score', models.IntegerField()),
                ('aptitude_score', models.IntegerField()),
                ('coding_score', models.IntegerField()),
                ('avg_test_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Treg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('organization', models.CharField(default='', max_length=200)),
                ('qualification', models.CharField(default='', max_length=200)),
                ('area_of_interest', models.CharField(default='', max_length=500)),
                ('experience', models.CharField(default='', max_length=100)),
                ('designation', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('pno', models.CharField(default='', max_length=10)),
                ('resume', models.FileField(default='settings.MEDIA_ROOT/TeacherResumes/sample.docx', upload_to='TeacherResumes/')),
            ],
        ),
    ]
