# Generated by Django 3.0.5 on 2022-04-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_jobapply_eq'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='codechef_stars',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='codechef_username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
