# Generated by Django 3.0.5 on 2022-05-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20220402_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproj',
            name='domain',
            field=models.CharField(default='Others', max_length=500),
        ),
        migrations.AddField(
            model_name='newproj',
            name='endorsement_count',
            field=models.IntegerField(default=0),
        ),
    ]
