# Generated by Django 3.0.5 on 2022-05-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20220508_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='endorsement_count',
            field=models.IntegerField(default=0),
        ),
    ]
