# Generated by Django 3.0.5 on 2022-05-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_jobapply_endorsement_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='endrosed_project_ids',
            field=models.CharField(default='', max_length=200),
        ),
    ]
